version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=question_answers
      - POSTGRES_PASSWORD=test
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ../efs/csv:/docker-entrypoint-initdb.d/csv
  redis_db:
    image: redis
    container_name: cache
    expose:
      - 6379
  server:
    build:
      # Specify where we want files to be pulled from
      context: .
      # Name of dockerfile
      dockerfile: Dockerfile.dev
    links:
      - redis_db
    expose:
      - '5000'
    volumes:
      - /app/node_modules
      - .:/app/
    environment:
      - REDIS_URL=redis://redis_db:6379
      - PGUSER=root
      - PGHOST=postgres
      - PGDATABASE=question_answers
      - PGPASSWORD=test
      - PGPORT=5432
  nginx:
    image: nginx:latest
    privileged: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - '3000:3000'
volumes:
  pgdata:
